package vn.studyroom;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/** PostgreSQL connection configured with STUDYROOM_DB_URL/USER/PASSWORD. */
public final class Database {
    private final String url;
    private final String user;
    private final String password;

    public Database() {
        url = setting("STUDYROOM_DB_URL", "jdbc:postgresql://localhost:5432/studyroom");
        user = setting("STUDYROOM_DB_USER", "postgres");
        password = setting("STUDYROOM_DB_PASSWORD", "");
        initialize();
    }

    public Connection connect() throws SQLException { return DriverManager.getConnection(url, user, password); }

    private static String setting(String name, String fallback) {
        String value = System.getenv(name);
        return value == null || value.isBlank() ? fallback : value;
    }

    private void initialize() {
        try (Connection connection = connect(); Statement statement = connection.createStatement()) {
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS app_user (
                  username VARCHAR(64) PRIMARY KEY,
                  display_name VARCHAR(100) NOT NULL,
                  password_hash VARCHAR(256) NOT NULL,
                  salt VARCHAR(128) NOT NULL,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
                """);
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS study_group (
                  room_id VARCHAR(64) PRIMARY KEY,
                  room_name VARCHAR(100) NOT NULL,
                  owner_username VARCHAR(64) NOT NULL REFERENCES app_user(username),
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
                """);
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS chat_message (
                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  room_id VARCHAR(64) NOT NULL,
                  sender VARCHAR(100) NOT NULL,
                  body VARCHAR(2000) NOT NULL,
                  sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
                """);
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS group_member (
                  room_id VARCHAR(64) NOT NULL REFERENCES study_group(room_id),
                  username VARCHAR(64) NOT NULL REFERENCES app_user(username),
                  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                  PRIMARY KEY (room_id, username)
                )
                """);
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS friendship (
                  sender VARCHAR(64) NOT NULL REFERENCES app_user(username),
                  receiver VARCHAR(64) NOT NULL REFERENCES app_user(username),
                  status VARCHAR(20) NOT NULL DEFAULT 'pending',
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                  PRIMARY KEY (sender, receiver)
                )
                """);
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS call_session (
                  call_id VARCHAR(64) PRIMARY KEY,
                  room_id VARCHAR(64) NOT NULL,
                  room_name VARCHAR(100) NOT NULL,
                  host_username VARCHAR(64) NOT NULL REFERENCES app_user(username),
                  call_type VARCHAR(20) NOT NULL,
                  status VARCHAR(20) NOT NULL,
                  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                )
                """);
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS call_participant (
                  call_id VARCHAR(64) NOT NULL REFERENCES call_session(call_id),
                  username VARCHAR(64) NOT NULL REFERENCES app_user(username),
                  display_name VARCHAR(100) NOT NULL,
                  status VARCHAR(20) NOT NULL,
                  udp_port INT DEFAULT 0,
                  joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                  PRIMARY KEY (call_id, username)
                )
                """);
        } catch (SQLException exception) { throw new IllegalStateException("Không thể khởi tạo Studyroom database.", exception); }
    }
}
